### ISSUE TITLE
PhpStorm hangs on project directory refresh

### ISSUE THREAD

**Issue by kamilw-kpl** [enriquepiatti/Magicento#54]
Hi!

I have this issue that when I perform some action which require to do a re-scan of directories, PhpStorm hangs and I cannot do anything except for kill the process. This action can be e.g. switching a branch in git.
This takes place after few hours of working. I can switch branches just after program started, but after a while (2-4h) on same action it dies.

After I kill the process and rerun the IDE is hangs on start up! I need to delete the cache files from .WebIde60/system/caches in order to make it work again! This is very painful, because a full index is created over again, which takes some time.

It's like since I've upgraded the plugin to 1.6 version

PhpStorm version 6.0.2
Magicento v. 1.6.2
OS Ubuntu 13.04 with Gnome Classic
Oracle JDK 1.6.0_45

I have made a request at PS bug tracker, yet they have found it is Magicento fault.

Here are links to some log files:
http://www.filedropper.com/idea
http://www.filedropper.com/threaddump

PS became so unstable so I uninstalled the plugin :( It's hard to work without it, so I hope you can help me.

Best regards

**Comment by enriquepiatti** [comment]
This happened to me too, I was working on some optimizations and I now I can't reproduce the error anymore, please add me to skype (enriquepiatti) if you want to test the lastest version? (not released yet).
Also, you can always download a prior Magicento version and install it manually.

**Comment by Haehnchen** [comment]
@enriquepiatti we all have the same issue:
https://github.com/adrienbrault/idea-php-symfony2-plugin/issues/52
http://devnet.jetbrains.com/message/5485912#5485912

the PhpTypes breaks alot on php reindexing
`getTypes(), resolve(), getReferences()` calls need to filter as much as possible

**Comment by enriquepiatti** [comment]
Fixed (I hope) in v.1.7.1
Please re-open if the problem persists

**Comment by kamilw-kpl** [comment]
When can we expect a release of version 1.7.1 of the plugin?

Edit.

Just installed the 1.7.1 version. Hope that hangs will stop :)

**Comment by enriquepiatti** [comment]
I can't reproduce the problem by myself but I know some other users are experimenting this so I'm reopening it :(

**Comment by amenk** [comment]
I am using Magicento 1.7.1 and PhpStorm 6.0.2
-- could it be cause by some old metadata in the project? (as an older Magicento was used before on the project)
I was able to solve it by deleting my module in .modman/TheModule and cloning the git of that modman module again.

**Comment by Haehnchen** [comment]
this is not a project issue. this is some phpstorm error. it looks like not only the mentioned calls freeze the ide. also simply call the `phpindex` on a bad time, when he is indexing breaks the process in a loop.

i wrap the calls into a cache hit like behavior:
https://github.com/adrienbrault/idea-php-symfony2-plugin/pull/64

i dont got a single freeze since using this.

**Comment by enriquepiatti** [comment]
I've opened an issue here:
http://youtrack.jetbrains.com/issue/WI-18517
but it was assigned to Alexey and he is on vacations now, so I think we won't get any response soon :(

**Comment by enriquepiatti** [comment]
should be fixed in v2.0.0

**Comment by TravisCornelius** [comment]
This is still happening.  It may have been my bad, but I did a search and replace for "if(" and replaced with "if (" for my entire project (5000+ places)  this was taking forever for i killed the phpstorm process. Once I reopened it I have been getting this error. I was on version 6.something

**Comment by enriquepiatti** [comment]
@TravisCornelius are you sure is related to Magicento? which version of Magicento are you using? also, you need at least PhpStorm 6.0.3
